### PR TITLE
HOTT-4358: Enable Origin Access Identities on s3 origins

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

https://transformuk.atlassian.net/browse/HOTT-4358

### What?

I have added/removed/altered:

- [x] Added resources to give the CDN permissions to access s3 buckets

### Why?

I am doing this because:

- You can't access a bucket as an OAI without permissions

### CODE REVIEW

**Review by amberstarlight — COMMENTED** [review]
We could probably create the access identity once per module instantiation, and support `s3_origin_config` too to plumb that together like so:

```hcl
origin {
    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.this.cloudfront_access_identity_path
    }
  }
```

**Comment by willfish** [comment]
I'm guessing we'll never want to serve content from different origins? e.g. static content from a bucket and dynamic content from an app, etc?

**Comment by amberstarlight** [comment]
> I'm guessing we'll never want to serve content from different origins? e.g. static content from a bucket and dynamic content from an app, etc?

We can have different origins, so the primary CDN routes to the load balancer with default forward to the frontend, for example.

An S3 bucket is just a secondary option - so we want to support both.

**Review by amberstarlight — APPROVED** [review]
LGTM

**Pull request merged**
